fixed again 	modified:   archinstaller

diff --git a/archinstaller b/archinstaller
--- a/archinstaller
+++ b/archinstaller
@@ -25,12 +25,13 @@ read installdrive
 sizeofdrive=$( /bin/df -h /dev/$installdrive --output=size -BG | sed -n 2p | tr -d 'G' )
 
 if [ $sizeofdrive \< 20 ];
-then
-   if [ $sizeofdrive \< 8 ];
-   then
-   		echo "ERROR: Drive is smaller then 8G, aborting, if you want to continue remove this line"; exit 1
-   else
-	echo "WARNING: Drive is smaller then 20G, A bigger drive is recommended, installing anyway.";
+	then
+  	 if [ $sizeofdrive \< 8 ];
+   			then
+   				echo "ERROR: Drive is smaller then 8G, aborting, if you want to continue remove this line"; exit 1
+   	fi
+		else
+			echo "WARNING: Drive is smaller then 20G, A bigger drive is recommended, installing anyway.";
 fi;
 
 if [ $sizeofdrive \> 32 ];
@@ -39,21 +40,22 @@ then
 	read homeseperate
 	
 	if [ $homeseperate != n]; 
-	then
-		homeseperate=yes && echo
+		then
+			homeseperate=yes && echo
 		
 		else
-		homeseperate=no
+			homeseperate=no
 	fi
 fi
 
 if [ $homeseperate = yes]; then
    echo "/home: Seperate from /"
-   else
+else
    echo "/home: Not seperate"
+fi
 
 /bin/echo -n "This is the last warning!  The installer will start installing on /dev/" $installdrive " in 5 seconds"
 /bin/sleep 5
 
 # /usr/sbin/parted /dev/$installdrive mklabel gpt 
-# /usr/sbin/parted -a optimal mkpart primary 0% 550MiB 
+# /usr/sbin/parted -a optimal /dev/$installdrive mkpart primary 0% 550MiB 
